# Files

This sink is designed for local logging to the files. It provides:

  * Simple logging into the one file;
  * Logging into different files simultaneousely according to the log event
  attributes;
  * Configurable log rotation mechanism.

**Files** sink is not thread-safe.

The first you need to do is to include special header:

~~~ cpp
#include <blackhole/sink/files.hpp>
~~~

## Registration
You should register this sink before use. To do it include the following code
into your program:

~~~ cpp
repository_t::instance().configure<
    sink::files_t<
        sink::files::boost_backend_t,
        sink::rotator_t<
            sink::files::boost_backend_t,
            sink::rotation::watcher::size_t
        >
    >,
    formatter::string_t
>();
~~~

The code above register **files** sink and **string**formatter pair. How to
register another combinations of sinks and formatters check the
[registration rules]() article.

After the registration this pair can be configured and used.

## Configuration

Example:
~~~ cpp
sink_config_t sink("files");
sink["path"] = "./logs/blackhole-%(log_event_attribute)s.log";
sink["autoflush"] = true;
sink["rotation"]["pattern"] = "%(filename)s.%N";
sink["rotation"]["backups"] = std::uint16_t(10);
sink["rotation"]["size"] = std::uint64_t(4*1024);
~~~

**Files** sink has the next configuration entities:

  * `path` - Absolute or relative path to the log file;
  * `autoflush` - Autoflush determines whether logs are dumped in the file
  immediately (`true` value), or accumulated in the internal buffer (`false`);
  * `rotation` - Set of rotation logic properties.

Below we will describe configuration entities `path` and `rotation` in details.

### Path
Path to the log file can contain placeholers in the next manner:

~~~ cpp
sink["path"] = "./logs/blackhole-%(log_event_attribute)s.log";
~~~

Blackhole allows to specify file pattern or determine real file name depending
on current log record's attributes set. [Logstash](http://logstash.net/) has
feature something like this, so if you familiar with Logstash, you'll be ok
here.

In our example there will be different files created with names depending on
`log_event_attribute` attribute's value. If `log_event_attribute` is "trace"
then all records will be written to the `blackhole-trace.log`.
For example:

~~~ cpp
BH_LOG(log, severity, "trace message")("log_event_attribute", "trace");
~~~

Using of placeholders is not necessary, so if you want to write all logs in one
file (say, blackhole.log), just don't use them.

### Rotation
Here come several rotation options, that determines file rotation settings. If
something defined in this section, Blackhole will create `files` sink with
rotation support, otherwise without one.

* Option `pattern` specifies pattern for backup files. Any name can be used
here, if you want to keep your backup names differently than the active file
name. For convenience the next placeholders can be also used:
    * Filename `%(filename)s` placeholder substitutes active file name.
    * Positional `%N` placeholder substitutes current backup position, starting
    with 1.
    * Date-time placeholders `%Y`, `%H`, `%M` etc. substitute the current
    values ​​of the corresponding fields.
* Option `backups` specifies maximum number of backup files. After reaching
that value older files will be replaced with the newer ones.
* Option `size` specifies active file('s) maximum size, after reacting that it
will be rotated.

Rotation works in the next manner. Blackhole writes logs into the log file
(`path`) until it exceeds `size`. At that moment log file is renamed according
to `pattern` and a new log file is started. Number of renamed files equals
to `backups`. When last `backups` number exceeded cycle is repeated.

?????????????????????????
*Note that also date-time rotation can be specified, e.g. each day or each
hour, but not now. More detailed it will be discussed in
reference documentation.
?????????????????????????

## Example
Example of `files`-sink usage you can find in the [tutorial]().
