# Features

## Core

## Sources

## Filtering

## Formatters

Formatters are entities that map log event to string. Blackhole supports three
built-in formatters:

  * [String](formatter/string). Maps log event to plain string by specified
  pattern with attributes support.
  * [JSON](formatter/json). Maps log event to JSON tree.
  * [Msgpack](formatter/msgpack). Maps log event to message-packed tree.

## Sinks

Sinks are designed for sending formatted message to its final destination.

Blackhole supports the next sinks out of the box:

  * [Null](sink/null). Transports messages to nowhere. Useful for testing or
  benchmarking.
  * [Elasticsearch](sink/elasticsearch). Client to [Elasticsearch](http://www.elasticsearch.org/) backend.
  * [Files](sink/files). Writes logs to the files. Supports log rotation.
  * [Socket](sink/socket). Sends messages through the network. Supports TCP
  and UDP.
  * [Stream](sink/stream). Supports `stdout` and `stderr` by default.
  * [Syslog](sink/syslog). Writes logs to `syslog`.

## Attributes

## Wrappers

## Exception Handling

## Mappers

## Repository

## External Initializatio
